# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: install
install:
	npm ci

.PHONY: lint
lint:
	npm run lint

.PHONY: lint-fix
lint-fix:
	npm run lint:fix

.PHONY: test-api
test-api:
	npm run test:api

.PHONY: test-e2e
test-e2e:
	sh cicd-scripts/run-prow-e2e.sh $1
