# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: install
install:
	npm config set prefix '.'
	export PATH=.:$PATH
	npm install

.PHONY: lint
lint:
	sudo npm run lint

.PHONY: check
check:
	sudo npm run check

.PHONY: unit-test
unit-test:
	sudo npm run test
